package fallback

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/songquanpeng/one-api/common/helper"
	"github.com/songquanpeng/one-api/common/logger"
	"github.com/songquanpeng/one-api/model"
	"github.com/songquanpeng/one-api/relay/adaptor/groq"
	"github.com/songquanpeng/one-api/relay/channeltype"
)

type FreeProviderMeta struct {
	ChannelType    int
	DefaultBaseURL string
	DefaultModels  []string
	DefaultRPM     int
	DefaultRPD     int
	DefaultTPM     int
	DefaultTPD     int
	ContextLength  int
	SupportsVision bool
	SupportsStream bool
	SupportsTools  bool
	SupportsJSON   bool
}

var BuiltinFreeProviders = map[string]FreeProviderMeta{
	"openrouter": {
		ChannelType:    channeltype.OpenRouter,
		DefaultBaseURL: "https://openrouter.ai/api",
		DefaultModels:  []string{"openrouter/free"},
		DefaultRPM:     20,
		ContextLength:  128000,
		SupportsStream: true,
	},
	"groq": {
		ChannelType:    channeltype.Groq,
		DefaultBaseURL: "https://api.groq.com/openai",
		DefaultModels:  []string{"mixtral-8x7b-32768", "llama-3.3-70b-versatile", "llama-3.1-8b-instant"},
		DefaultRPM:     30,
		DefaultTPM:     6000,
		ContextLength:  32768,
		SupportsStream: true,
		SupportsTools:  true,
		SupportsJSON:   true,
	},
	"freellmapi": {
		ChannelType:    channeltype.OpenAICompatible,
		DefaultBaseURL: "https://TODO.freellmapi/v1", // TODO: 真实端点未上线,占位;上线后替换
		DefaultModels:  []string{},
		DefaultRPM:     10,
		ContextLength:  32768,
		SupportsStream: true,
	},
	"kilo": {
		ChannelType:    channeltype.OpenAICompatible,
		DefaultBaseURL: "https://api.kilo.ai/api/gateway/v1",
		DefaultModels:  []string{}, // 由 fetchModels 动态拉取
		DefaultRPM:     10,
		ContextLength:  256000,
		SupportsStream: true,
	},
}

const autoChannelPrefix = "[CCT Auto] "

func channelName(provider string, keyHash string) string {
	return autoChannelPrefix + provider + "-" + keyHash
}

func deploymentID(provider string, keyHash string) string {
	return "free:" + provider + "-" + keyHash
}

// SafeKeyHash returns a short 8-char hex hash of the API key for use in
// auto-generated channel names and deployment IDs. Uses first 4 bytes of
// SHA256 — enough to distinguish keys without exposing the full key.
func SafeKeyHash(key string) string {
	h := sha256.Sum256([]byte(key))
	return hex.EncodeToString(h[:4])
}

// knownFreeProviders lists providers that SyncFreePool can auto-manage.
// Used to distinguish auto-generated IDs from user-created ones.
var knownFreeProviders = map[string]struct{}{
	"openrouter": {},
	"groq":       {},
	"freellmapi": {},
	"kilo":       {},
}

// isAutoDeploymentSuffix validates the suffix portion of an auto-generated
// channel name or deployment ID. Accepts both the old integer index format
// (e.g. "0", "1") and the new 8-char hex hash format (e.g. "a1b2c3d4").
func isAutoDeploymentSuffix(suffix string) bool {
	// Old format: integer index
	if _, err := strconv.Atoi(suffix); err == nil {
		return true
	}
	// New format: 8-char hex hash
	if len(suffix) == 8 {
		_, err := hex.DecodeString(suffix)
		return err == nil
	}
	return false
}

// IsAutoDeploymentID returns true if the deployment ID was auto-generated by SyncFreePool.
// Strictly matches "free:{known_provider}-{suffix}" pattern where suffix is either
// an integer index (old format) or an 8-char hex hash (new format).
// User-created "free:*" IDs are excluded as they don't match known providers.
func IsAutoDeploymentID(id string) bool {
	for prov := range knownFreeProviders {
		prefix := "free:" + prov + "-"
		if strings.HasPrefix(id, prefix) {
			suffix := strings.TrimPrefix(id, prefix)
			return isAutoDeploymentSuffix(suffix)
		}
	}
	return false
}

// IsAutoChannelName returns true if the channel name was auto-generated by SyncFreePool.
// Strictly matches "[CCT Auto] {known_provider}-{suffix}" pattern.
func IsAutoChannelName(name string) bool {
	for prov := range knownFreeProviders {
		prefix := autoChannelPrefix + prov + "-"
		if strings.HasPrefix(name, prefix) {
			suffix := strings.TrimPrefix(name, prefix)
			return isAutoDeploymentSuffix(suffix)
		}
	}
	return false
}

func SyncFreePool(cfg *Config) error {
	if cfg == nil || !cfg.Enabled {
		return nil
	}

	// 1. Scan existing auto channels
	// Note: escape [ and ] in LIKE — SQL treats [] as character class wildcard
	var existing []*model.Channel
	if err := model.DB.Where("name LIKE ?", autoChannelPrefix+"%").Find(&existing).Error; err != nil {
		return fmt.Errorf("failed to query auto channels: %w", err)
	}
	existingByName := map[string]*model.Channel{}
	for _, ch := range existing {
		existingByName[ch.Name] = ch
	}

	// 2. Compute desired channels and collect deployments
	type desired struct {
		name     string
		ch       model.Channel
		provider string
		keyHash  string
	}
	var desiredChannels []desired
	// Preserve existing non-auto deployments (collect them first)
	autoDeployments := map[string]DeploymentConfig{}

	for providerName, fp := range cfg.FreeProviders {
		meta, ok := BuiltinFreeProviders[providerName]
		if !ok {
			logger.SysWarn(fmt.Sprintf("[free_pool] unknown provider %q, skipping", providerName))
			continue
		}
		if !fp.Enabled || len(fp.Keys) == 0 {
			continue
		}

		models := fp.Models
		if len(models) == 0 {
			models = meta.DefaultModels
		}
		realModel := models[0]

		for _, key := range fp.Keys {
			if strings.TrimSpace(key) == "" {
				continue
			}
			keyHash := SafeKeyHash(key)
			name := channelName(providerName, keyHash)
			now := helper.GetTimestamp()
			weight := uint(0)
			baseURL := meta.DefaultBaseURL
			ch := model.Channel{
				Name:        name,
				Type:        meta.ChannelType,
				Key:         strings.TrimSpace(key),
				BaseURL:     &baseURL,
				Models:      strings.Join(models, ","),
				Status:      model.ChannelStatusEnabled,
				Weight:      &weight,
				CreatedTime: now,
			}
			desiredChannels = append(desiredChannels, desired{name, ch, providerName, keyHash})

			// Build deployment
			rpm := fp.DefaultRPM
			if rpm <= 0 {
				rpm = meta.DefaultRPM
			}
			rpd := fp.DefaultRPD
			if rpd <= 0 {
				rpd = meta.DefaultRPD
			}
			tpm := fp.DefaultTPM
			if tpm <= 0 {
				tpm = meta.DefaultTPM
			}
			tpd := fp.DefaultTPD
			if tpd <= 0 {
				tpd = meta.DefaultTPD
			}

			// Apply limits_override on top of merged defaults
			rpm, rpd, tpm, tpd = ApplyLimitsOverride(rpm, rpd, tpm, tpd, fp.LimitsOverride)

			depID := deploymentID(providerName, keyHash)
			autoDeployments[depID] = DeploymentConfig{
				ID:                    depID,
				Enabled:               true,
				ChannelID:             0, // filled after channel insert/update
				RealModel:             realModel,
				Pool:                  "free",
				QualityTier:           "medium",
				CostTier:              "free",
				SupportsVision:        meta.SupportsVision,
				SupportsStream:        meta.SupportsStream,
				SupportsTools:         meta.SupportsTools,
				SupportsJSON:          meta.SupportsJSON,
				ContextLength:         meta.ContextLength,
				Priority:              10,
				Weight:                100,
				MaxConcurrentRequests: 5,
				QuotaMode:             "free",
				SoftLimitRatio:        0.95,
				HardLimitRatio:        1.0,
				RPMLimit:              rpm,
				RPDLimit:              rpd,
				TPMLimit:              tpm,
				TPDLimit:              tpd,
			}
		}
	}

	// 3. Reconcile channels
	for _, d := range desiredChannels {
		existingCh, found := existingByName[d.name]
		if found {
			// Update if key changed
			if existingCh.Key != d.ch.Key {
				existingCh.Key = d.ch.Key
				existingCh.Models = d.ch.Models
				existingCh.Type = d.ch.Type
				if err := model.DB.Model(existingCh).Updates(map[string]interface{}{
					"key":    existingCh.Key,
					"models": existingCh.Models,
					"type":   existingCh.Type,
				}).Error; err != nil {
					logger.SysError(fmt.Sprintf("[free_pool] failed to update channel %s: %v", d.name, err))
					continue
				}
				_ = existingCh.UpdateAbilities()
				logger.SysWarn(fmt.Sprintf("[free_pool] auto channel %s (id=%d) key updated — config sync overwrote previous key", d.name, existingCh.Id))
			}
			// Ensure enabled
			if existingCh.Status != model.ChannelStatusEnabled {
				model.UpdateChannelStatusById(existingCh.Id, model.ChannelStatusEnabled)
			}
			// Fill ChannelID in deployment
			depID := deploymentID(d.provider, d.keyHash)
			if dep, ok := autoDeployments[depID]; ok {
				dep.ChannelID = existingCh.Id
				autoDeployments[depID] = dep
			}
		} else {
			// Create new channel
			if err := d.ch.Insert(); err != nil {
				logger.SysError(fmt.Sprintf("[free_pool] failed to insert channel %s: %v", d.name, err))
				continue
			}
			// Fill ChannelID in deployment
			depID := deploymentID(d.provider, d.keyHash)
			if dep, ok := autoDeployments[depID]; ok {
				dep.ChannelID = d.ch.Id
				autoDeployments[depID] = dep
			}
		}
	}

	// 4. Disable removed channels
	for _, existingCh := range existing {
		stillNeeded := false
		for _, d := range desiredChannels {
			if d.name == existingCh.Name {
				stillNeeded = true
				break
			}
		}
		if !stillNeeded && existingCh.Status == model.ChannelStatusEnabled {
			model.UpdateChannelStatusById(existingCh.Id, model.ChannelStatusManuallyDisabled)
			logger.SysLog(fmt.Sprintf("[free_pool] disabled removed auto channel %s (id=%d)", existingCh.Name, existingCh.Id))
		}
	}

	// 5. Write auto deployments into cfg.Deployments (merge, don't wipe).
	// Only write deployments whose ID matches IsAutoDeploymentID — user-created
	// deployments with a "free:*" prefix are preserved and never overwritten.
	if cfg.Deployments == nil {
		cfg.Deployments = map[string]DeploymentConfig{}
	}
	for id, dep := range autoDeployments {
		if dep.ChannelID <= 0 {
			logger.SysWarn(fmt.Sprintf("[free_pool] skipping deployment %s with no channel", id))
			continue
		}
		cfg.Deployments[id] = dep
	}

	// 6. Clean up stale auto deployments: remove from cfg.Deployments any auto
	// deployment that no longer has a corresponding enabled channel.
	for id := range cfg.Deployments {
		if !IsAutoDeploymentID(id) {
			continue // skip user-created deployments
		}
		if _, active := autoDeployments[id]; !active {
			// Stale: either the provider was disabled or the key was removed.
			// Remove it from the config so it won't be considered for routing.
			delete(cfg.Deployments, id)
			logger.SysLog(fmt.Sprintf("[free_pool] removed stale auto deployment %s (channel no longer active)", id))
		}
	}

	return nil
}

func ValidateFreeProviderName(name string) error {
	if _, ok := BuiltinFreeProviders[name]; !ok {
		known := make([]string, 0, len(BuiltinFreeProviders))
		for k := range BuiltinFreeProviders {
			known = append(known, k)
		}
		return fmt.Errorf("unknown free provider %q, known: %s", name, strings.Join(known, ", "))
	}
	return nil
}

func init() {
	_ = time.Now
}

// ApplyLimitsOverride applies limits_override fields on top of existing int values.
// Each non-nil pointer in override replaces the corresponding value.
// Zero means unlimited (valid). Negative values should be rejected by ValidateFreeProviderLimits
// before reaching this function.
func ApplyLimitsOverride(rpm, rpd, tpm, tpd int, override *FreeProviderLimits) (int, int, int, int) {
	if override == nil {
		return rpm, rpd, tpm, tpd
	}
	if override.RPMLimit != nil {
		rpm = *override.RPMLimit
	}
	if override.RPDLimit != nil {
		rpd = *override.RPDLimit
	}
	if override.TPMLimit != nil {
		tpm = *override.TPMLimit
	}
	if override.TPDLimit != nil {
		tpd = *override.TPDLimit
	}
	return rpm, rpd, tpm, tpd
}

// ValidateFreeProviderLimits checks that all limits_override values are >= 0.
func ValidateFreeProviderLimits(limits *FreeProviderLimits) error {
	if limits == nil {
		return nil
	}
	if limits.RPMLimit != nil && *limits.RPMLimit < 0 {
		return fmt.Errorf("rpm_limit must be >= 0, got %d", *limits.RPMLimit)
	}
	if limits.RPDLimit != nil && *limits.RPDLimit < 0 {
		return fmt.Errorf("rpd_limit must be >= 0, got %d", *limits.RPDLimit)
	}
	if limits.TPMLimit != nil && *limits.TPMLimit < 0 {
		return fmt.Errorf("tpm_limit must be >= 0, got %d", *limits.TPMLimit)
	}
	if limits.TPDLimit != nil && *limits.TPDLimit < 0 {
		return fmt.Errorf("tpd_limit must be >= 0, got %d", *limits.TPDLimit)
	}
	return nil
}

// StaleCleanupReport describes auto-generated resources that exist but no longer
// have a corresponding entry in the current free_providers config.
type StaleCleanupReport struct {
	StaleChannels    []StaleItem `json:"stale_channels"`
	StaleDeployments []StaleItem `json:"stale_deployments"`
	WillDelete       bool        `json:"will_delete"`
}

// StaleItem represents a single stale auto resource.
type StaleItem struct {
	Name   string `json:"name"`
	ID     int    `json:"id,omitempty"`
	Reason string `json:"reason"`
}

// computeExpectedAutoResources computes the set of expected auto channel names
// and deployment IDs from the current FreeProviders config. Used by both
// DryRunCleanStale and tests to determine which auto resources are still valid.
func computeExpectedAutoResources(cfg *Config) (expectedChannels map[string]bool, expectedDeployments map[string]bool) {
	expectedChannels = make(map[string]bool)
	expectedDeployments = make(map[string]bool)

	for providerName, fp := range cfg.FreeProviders {
		if !fp.Enabled || len(fp.Keys) == 0 {
			continue
		}
		if _, ok := BuiltinFreeProviders[providerName]; !ok {
			continue
		}
		for _, key := range fp.Keys {
			if strings.TrimSpace(key) == "" {
				continue
			}
			keyHash := SafeKeyHash(key)
			expectedChannels[channelName(providerName, keyHash)] = true
			expectedDeployments[deploymentID(providerName, keyHash)] = true
		}
	}
	return expectedChannels, expectedDeployments
}

// DryRunCleanStale returns a report of stale auto resources (channels and
// deployments) that exist in the DB or config but no longer have a matching
// entry in the current free_providers config. Does NOT mutate any state.
// Report is non-nil even when an error is returned.
func DryRunCleanStale() (*StaleCleanupReport, error) {
	cfg := GetConfig()
	if cfg == nil {
		return &StaleCleanupReport{WillDelete: false}, fmt.Errorf("config is nil")
	}

	report := &StaleCleanupReport{WillDelete: false}
	expectedChannels, expectedDeployments := computeExpectedAutoResources(cfg)

	// Scan DB for auto channels that no longer have a matching config entry
	if model.DB == nil {
		return report, fmt.Errorf("database not initialized")
	}

	var dbChannels []*model.Channel
	if err := model.DB.Where("name LIKE ?", autoChannelPrefix+"%").Find(&dbChannels).Error; err != nil {
		return report, fmt.Errorf("failed to query auto channels: %w", err)
	}

	for _, ch := range dbChannels {
		if !expectedChannels[ch.Name] {
			report.StaleChannels = append(report.StaleChannels, StaleItem{
				Name:   ch.Name,
				ID:     ch.Id,
				Reason: "not found in current free_providers config",
			})
		}
	}

	// Scan config deployments for auto deployments that no longer have a matching key
	if cfg.Deployments != nil {
		for id, dep := range cfg.Deployments {
			if !IsAutoDeploymentID(id) {
				continue
			}
			if !expectedDeployments[id] {
				report.StaleDeployments = append(report.StaleDeployments, StaleItem{
					Name:   id,
					ID:     dep.ChannelID,
					Reason: "not found in current free_providers config",
				})
			}
		}
	}

	// Sort for deterministic output
	sort.Slice(report.StaleChannels, func(i, j int) bool {
		return report.StaleChannels[i].Name < report.StaleChannels[j].Name
	})
	sort.Slice(report.StaleDeployments, func(i, j int) bool {
		return report.StaleDeployments[i].Name < report.StaleDeployments[j].Name
	})

	return report, nil
}

// ===== 缺口2: 模型动态获取 + 缺口4: OpenRouter 配额同步 =====
//
// 两个外部拉取操作(fetchModels / queryOpenRouterCredits)共用同一套 HTTP 模式:
// client.ImpatientHTTPClient(5s 超时) + Bearer key + json.Unmarshal。
// 定时器入口 StartFreeSync 照抄 health.go 的 StartHealthChecker 守卫模式。

// openRouterModelsResponse 是 OpenRouter GET /v1/models 的响应结构。
type openRouterModelsResponse struct {
	Data []struct {
		ID string `json:"id"`
	} `json:"data"`
}

// openRouterCreditsResponse 是 OpenRouter GET /v1/credits 的响应结构。
type openRouterCreditsResponse struct {
	Data struct {
		TotalCredits float64 `json:"total_credits"`
		TotalUsage   float64 `json:"total_usage"`
	} `json:"data"`
}

// fetchModels 拉取指定 provider 的可用模型列表。
//   - openrouter: GET /v1/models,过滤 :free 后缀,去重排序
//   - groq: 直接返静态 groq.ModelList,不网络拉
//   - freellmapi: 占位 URL,返 meta.DefaultModels(当前空)+ warn,不拉
//   - kilo: GET /models,过滤 isFree:true,去重排序
//
// 失败返 error,调用方降级到静态默认。不在持有任何锁时调用。
func fetchModels(providerName, key string) ([]string, error) {
	switch providerName {
	case "groq":
		return groq.ModelList, nil
	case "freellmapi":
		// ponytail: 占位端点未上线,不拉,返空让调用方用静态默认
		logger.SysWarn("[free-pool] freellmapi endpoint not live yet, skipping model fetch")
		return BuiltinFreeProviders["freellmapi"].DefaultModels, nil
	case "openrouter":
		return fetchOpenRouterModels(key)
	case "kilo":
		return fetchKiloModels()
	default:
		return nil, fmt.Errorf("fetchModels: unsupported provider %q", providerName)
	}
}

func fetchOpenRouterModels(key string) ([]string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet,
		"https://openrouter.ai/api/v1/models", nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Authorization", "Bearer "+key)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("openrouter /v1/models request: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("openrouter /v1/models status %d", resp.StatusCode)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read models body: %w", err)
	}
	return parseFreeModels(body)
}

// parseFreeModels 解析 OpenRouter /v1/models 响应体,过滤 :free 后缀,去重排序。
// 抽成纯函数便于单测(不需打真实 HTTP)。
func parseFreeModels(body []byte) ([]string, error) {
	var respData openRouterModelsResponse
	if err := json.Unmarshal(body, &respData); err != nil {
		return nil, fmt.Errorf("parse models json: %w", err)
	}
	seen := make(map[string]struct{}, len(respData.Data))
	var free []string
	for _, m := range respData.Data {
		if strings.HasSuffix(m.ID, ":free") {
			if _, ok := seen[m.ID]; !ok {
				seen[m.ID] = struct{}{}
				free = append(free, m.ID)
			}
		}
	}
	sort.Strings(free)
	return free, nil
}

// Kilo API 响应结构
type kiloModelsResponse struct {
	Data []struct {
		ID     string `json:"id"`
		IsFree bool   `json:"isFree"`
	} `json:"data"`
}

// fetchKiloModels 调用 Kilo /models 端点,过滤 isFree:true,去重排序。
// Kilo 是 keyless 供应商，无需 API key。
func fetchKiloModels() ([]string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet,
		"https://api.kilo.ai/api/gateway/models", nil)
	if err != nil {
		return nil, err
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("kilo /models request: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("kilo /models status %d", resp.StatusCode)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read kilo models body: %w", err)
	}
	return parseKiloFreeModels(body)
}

// parseKiloFreeModels 解析 Kilo /models 响应体,过滤 isFree:true,去重排序。
func parseKiloFreeModels(body []byte) ([]string, error) {
	var respData kiloModelsResponse
	if err := json.Unmarshal(body, &respData); err != nil {
		return nil, fmt.Errorf("parse kilo models json: %w", err)
	}
	seen := make(map[string]struct{}, len(respData.Data))
	var free []string
	for _, m := range respData.Data {
		if m.IsFree {
			if _, ok := seen[m.ID]; !ok {
				seen[m.ID] = struct{}{}
				free = append(free, m.ID)
			}
		}
	}
	sort.Strings(free)
	return free, nil
}

// syncAllProviderModels 是通用的模型同步入口:遍历 cfg.FreeProviders 中
// 所有 Enabled 条目,对每个供应商的每个 key 调 fetchModels,
// 成功则更新对应 channel 的 Models 字段;
// 失败 log warn 保静态默认,不动 channel。
// 仅操作传入的 cfg(调用方负责锁),不在持有 configLock 时调 HTTP。
// keyless 供应商（如 kilo）用空 key,fetchModels 会处理。
func syncAllProviderModels(cfg *Config) {
	if cfg == nil || cfg.FreeProviders == nil {
		return
	}
	for providerName, fp := range cfg.FreeProviders {
		if !fp.Enabled {
			continue
		}
		// keyless 供应商:用空 key 调一次 fetchModels
		if len(fp.Keys) == 0 {
			models, err := fetchModels(providerName, "")
			if err != nil {
				logger.SysWarn(fmt.Sprintf("[free-pool] %s model fetch failed: %v (keeping static default)", providerName, err))
				continue
			}
			if len(models) == 0 {
				logger.SysWarn(fmt.Sprintf("[free-pool] %s returned no models (keeping static default)", providerName))
				continue
			}
			// keyless 供应商只有一个 channel,用空 key 的 hash
			keyHash := SafeKeyHash("")
			name := channelName(providerName, keyHash)
			var ch model.Channel
			if err := model.DB.Where("name = ?", name).First(&ch).Error; err != nil {
				logger.SysWarn(fmt.Sprintf("[free-pool] %s channel %s not found in DB: %v", providerName, name, err))
				continue
			}
			newModels := strings.Join(models, ",")
			if ch.Models == newModels {
				continue // 无变化,跳过
			}
			if err := model.DB.Model(&ch).Update("models", newModels).Error; err != nil {
				logger.SysError(fmt.Sprintf("[free-pool] failed to update models for %s: %v", name, err))
				continue
			}
			ch.Models = newModels
			_ = ch.UpdateAbilities()
			logger.SysLog(fmt.Sprintf("[free-pool] %s %s models synced: %d models", providerName, name, len(models)))
			continue
		}
		// 有 key 的供应商:遍历每个 key
		for _, key := range fp.Keys {
			key = strings.TrimSpace(key)
			if key == "" {
				continue
			}
			keyHash := SafeKeyHash(key)
			depID := deploymentID(providerName, keyHash)
			models, err := fetchModels(providerName, key)
			if err != nil {
				logger.SysWarn(fmt.Sprintf("[free-pool] %s model fetch failed for %s: %v (keeping static default)", providerName, depID, err))
				continue
			}
			if len(models) == 0 {
				logger.SysWarn(fmt.Sprintf("[free-pool] %s returned no models for %s (keeping static default)", providerName, depID))
				continue
			}
			// ponytail: 不更新 cfg.Deployments[depID].RealModel — GetConfig() 返的是快照副本，
			// 写了也丢。路由靠 DB channel.Models（下面更新），deployment.RealModel 由
			// SyncFreePool/ReloadConfig 从静态 config 设置，这里是动态补充。
			// 更新 channel Models 字段(照抄 SyncFreePool L255-263 更新模式)
			name := channelName(providerName, keyHash)
			var ch model.Channel
			if err := model.DB.Where("name = ?", name).First(&ch).Error; err != nil {
				logger.SysWarn(fmt.Sprintf("[free-pool] %s channel %s not found in DB: %v", providerName, name, err))
				continue
			}
			newModels := strings.Join(models, ",")
			if ch.Models == newModels {
				continue // 无变化,跳过
			}
			if err := model.DB.Model(&ch).Update("models", newModels).Error; err != nil {
				logger.SysError(fmt.Sprintf("[free-pool] failed to update models for %s: %v", name, err))
				continue
			}
			ch.Models = newModels
			_ = ch.UpdateAbilities()
			logger.SysLog(fmt.Sprintf("[free-pool] %s %s models synced: %d models", providerName, name, len(models)))
		}
	}
}

// queryOpenRouterCredits 拉 OpenRouter /v1/credits,返余额(美元)= total_credits - total_usage。
func queryOpenRouterCredits(key string) (float64, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet,
		"https://openrouter.ai/api/v1/credits", nil)
	if err != nil {
		return 0, err
	}
	req.Header.Set("Authorization", "Bearer "+key)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return 0, fmt.Errorf("openrouter /v1/credits request: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return 0, fmt.Errorf("openrouter /v1/credits status %d", resp.StatusCode)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return 0, fmt.Errorf("read credits body: %w", err)
	}
	return parseCreditsBalance(body)
}

// parseCreditsBalance 解析 OpenRouter /v1/credits 响应体,返余额=total_credits-total_usage。
// 抽成纯函数便于单测。
func parseCreditsBalance(body []byte) (float64, error) {
	var respData openRouterCreditsResponse
	if err := json.Unmarshal(body, &respData); err != nil {
		return 0, fmt.Errorf("parse credits json: %w", err)
	}
	return respData.Data.TotalCredits - respData.Data.TotalUsage, nil
}

// syncOpenRouterCredits 是缺口4 的同步入口:遍历 openrouter,每 key 调
// queryOpenRouterCredits,算 tokens = balance * 1e6 / 7.5(OpenRouter 定价
// $7.5/1M tokens 的粗估),调 UpdateDeploymentDailyLimit 落到内存 config。
// 返更新数。不在持有 configLock 时调 HTTP —— 先拿 cfg 快照裸调 HTTP,
// 再 UpdateDeploymentDailyLimit(自己拿写锁)。
func syncOpenRouterCredits(cfg *Config) int {
	if cfg == nil || cfg.FreeProviders == nil {
		return 0
	}
	fp, ok := cfg.FreeProviders["openrouter"]
	if !ok || !fp.Enabled || len(fp.Keys) == 0 {
		return 0
	}
	updated := 0
	for _, key := range fp.Keys {
		key = strings.TrimSpace(key)
		if key == "" {
			continue
		}
		depID := deploymentID("openrouter", SafeKeyHash(key))
		balance, err := queryOpenRouterCredits(key)
		if err != nil {
			logger.SysWarn(fmt.Sprintf("[free-pool] openrouter credits query failed for %s: %v", depID, err))
			continue
		}
		if balance <= 0 {
			continue
		}
		// ponytail: $7.5/1M tokens 的粗估换算;真实定价按模型不同,
		// 但 free 模型实际不扣费,这里只是给 DailyLimitTokens 一个合理量级
		tokens := int64(balance * 1_000_000 / 7.5)
		if tokens <= 0 {
			continue
		}
		UpdateDeploymentDailyLimit(depID, tokens)
		updated++
	}
	if updated > 0 {
		logger.SysLog(fmt.Sprintf("[free-pool] soft-synced %d free deployment(s) from OpenRouter /v1/credits", updated))
	}
	return updated
}

// freeSyncRunning / freeSyncStopCh 守卫 StartFreeSync,照抄 health.go 的
// globalHealth 模式,防重复启动 + 支持优雅停止。
var (
	freeSyncRunning bool
	freeSyncStopCh  chan struct{}
	freeSyncMu      sync.Mutex
)

// StartFreeSync 启动两个后台 goroutine:fetch 模型(6h)和同步配额(15m)。
// 启动后立即各 warm-up 一次。stopCh 非 nil 时监听退出,nil 则跟随进程生命周期。
// 由 main.go 在 StartHealthChecker 旁调一次。
func StartFreeSync(stopCh chan struct{}) {
	freeSyncMu.Lock()
	if freeSyncRunning {
		freeSyncMu.Unlock()
		return
	}
	freeSyncRunning = true
	freeSyncStopCh = stopCh
	freeSyncMu.Unlock()

	go runFreeSyncModels()
	go runFreeSyncCredits()
	logger.SysLog("[free-pool] free sync started: models 6h, credits 15m")
}

func runFreeSyncModels() {
	// warm-up 一次,再进 6h ticker
	syncAllProviderModels(GetConfig())
	ticker := time.NewTicker(6 * time.Hour)
	defer ticker.Stop()
	for {
		select {
		case <-ticker.C:
			syncAllProviderModels(GetConfig())
		case <-freeSyncStopSignal():
			return
		}
	}
}

func runFreeSyncCredits() {
	// warm-up 一次,再进 15m ticker
	syncOpenRouterCredits(GetConfig())
	ticker := time.NewTicker(15 * time.Minute)
	defer ticker.Stop()
	for {
		select {
		case <-ticker.C:
			syncOpenRouterCredits(GetConfig())
		case <-freeSyncStopSignal():
			return
		}
	}
}

// freeSyncStopSignal 返回一个停止信号 channel。stopCh 为 nil 时
// 返 nil(select 对 nil channel 永久阻塞,即不主动停,跟随进程)。
func freeSyncStopSignal() <-chan struct{} {
	freeSyncMu.Lock()
	defer freeSyncMu.Unlock()
	if freeSyncStopCh == nil {
		return nil
	}
	return freeSyncStopCh
}
