package fallback

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/songquanpeng/one-api/common/helper"
	"github.com/songquanpeng/one-api/common/logger"
	"github.com/songquanpeng/one-api/model"
	"github.com/songquanpeng/one-api/relay/channeltype"
)

type FreeProviderMeta struct {
	ChannelType    int
	DefaultBaseURL string
	DefaultModels  []string
	DefaultRPM     int
	DefaultRPD     int
	DefaultTPM     int
	DefaultTPD     int
	ContextLength  int
	SupportsVision bool
	SupportsStream bool
	SupportsTools  bool
	SupportsJSON   bool
}

var BuiltinFreeProviders = map[string]FreeProviderMeta{
	"openrouter": {
		ChannelType:    channeltype.OpenRouter,
		DefaultBaseURL: "https://openrouter.ai/api",
		DefaultModels:  []string{"openrouter/free"},
		DefaultRPM:     20,
		ContextLength:  128000,
		SupportsStream: true,
	},
	"groq": {
		ChannelType:    channeltype.Groq,
		DefaultBaseURL: "https://api.groq.com/openai",
		DefaultModels:  []string{"mixtral-8x7b-32768", "llama-3.3-70b-versatile", "llama-3.1-8b-instant"},
		DefaultRPM:     30,
		DefaultTPM:     6000,
		ContextLength:  32768,
		SupportsStream: true,
		SupportsTools:  true,
		SupportsJSON:   true,
	},
}

const autoChannelPrefix = "[CCT Auto] "

func channelName(provider string, keyHash string) string {
	return autoChannelPrefix + provider + "-" + keyHash
}

func deploymentID(provider string, keyHash string) string {
	return "free:" + provider + "-" + keyHash
}

// SafeKeyHash returns a short 8-char hex hash of the API key for use in
// auto-generated channel names and deployment IDs. Uses first 4 bytes of
// SHA256 — enough to distinguish keys without exposing the full key.
func SafeKeyHash(key string) string {
	h := sha256.Sum256([]byte(key))
	return hex.EncodeToString(h[:4])
}

// knownFreeProviders lists providers that SyncFreePool can auto-manage.
// Used to distinguish auto-generated IDs from user-created ones.
var knownFreeProviders = map[string]struct{}{
	"openrouter": {},
	"groq":       {},
}

// isAutoDeploymentSuffix validates the suffix portion of an auto-generated
// channel name or deployment ID. Accepts both the old integer index format
// (e.g. "0", "1") and the new 8-char hex hash format (e.g. "a1b2c3d4").
func isAutoDeploymentSuffix(suffix string) bool {
	// Old format: integer index
	if _, err := strconv.Atoi(suffix); err == nil {
		return true
	}
	// New format: 8-char hex hash
	if len(suffix) == 8 {
		_, err := hex.DecodeString(suffix)
		return err == nil
	}
	return false
}

// IsAutoDeploymentID returns true if the deployment ID was auto-generated by SyncFreePool.
// Strictly matches "free:{known_provider}-{suffix}" pattern where suffix is either
// an integer index (old format) or an 8-char hex hash (new format).
// User-created "free:*" IDs are excluded as they don't match known providers.
func IsAutoDeploymentID(id string) bool {
	for prov := range knownFreeProviders {
		prefix := "free:" + prov + "-"
		if strings.HasPrefix(id, prefix) {
			suffix := strings.TrimPrefix(id, prefix)
			return isAutoDeploymentSuffix(suffix)
		}
	}
	return false
}

// IsAutoChannelName returns true if the channel name was auto-generated by SyncFreePool.
// Strictly matches "[CCT Auto] {known_provider}-{suffix}" pattern.
func IsAutoChannelName(name string) bool {
	for prov := range knownFreeProviders {
		prefix := autoChannelPrefix + prov + "-"
		if strings.HasPrefix(name, prefix) {
			suffix := strings.TrimPrefix(name, prefix)
			return isAutoDeploymentSuffix(suffix)
		}
	}
	return false
}

func SyncFreePool(cfg *Config) error {
	if cfg == nil || !cfg.Enabled {
		return nil
	}

	// 1. Scan existing auto channels
	// Note: escape [ and ] in LIKE — SQL treats [] as character class wildcard
	var existing []*model.Channel
	if err := model.DB.Where("name LIKE ?", autoChannelPrefix+"%").Find(&existing).Error; err != nil {
		return fmt.Errorf("failed to query auto channels: %w", err)
	}
	existingByName := map[string]*model.Channel{}
	for _, ch := range existing {
		existingByName[ch.Name] = ch
	}

	// 2. Compute desired channels and collect deployments
	type desired struct {
		name     string
		ch       model.Channel
		provider string
		keyHash  string
	}
	var desiredChannels []desired
	// Preserve existing non-auto deployments (collect them first)
	autoDeployments := map[string]DeploymentConfig{}

	for providerName, fp := range cfg.FreeProviders {
		meta, ok := BuiltinFreeProviders[providerName]
		if !ok {
			logger.SysWarn(fmt.Sprintf("[free_pool] unknown provider %q, skipping", providerName))
			continue
		}
		if !fp.Enabled || len(fp.Keys) == 0 {
			continue
		}

		models := fp.Models
		if len(models) == 0 {
			models = meta.DefaultModels
		}
		realModel := models[0]

		for _, key := range fp.Keys {
			if strings.TrimSpace(key) == "" {
				continue
			}
			keyHash := SafeKeyHash(key)
			name := channelName(providerName, keyHash)
			now := helper.GetTimestamp()
			weight := uint(0)
			baseURL := meta.DefaultBaseURL
			ch := model.Channel{
				Name:        name,
				Type:        meta.ChannelType,
				Key:         strings.TrimSpace(key),
				BaseURL:     &baseURL,
				Models:      strings.Join(models, ","),
				Status:      model.ChannelStatusEnabled,
				Weight:      &weight,
				CreatedTime: now,
			}
			desiredChannels = append(desiredChannels, desired{name, ch, providerName, keyHash})

			// Build deployment
			rpm := fp.DefaultRPM
			if rpm <= 0 {
				rpm = meta.DefaultRPM
			}
			rpd := fp.DefaultRPD
			if rpd <= 0 {
				rpd = meta.DefaultRPD
			}
			tpm := fp.DefaultTPM
			if tpm <= 0 {
				tpm = meta.DefaultTPM
			}
			tpd := fp.DefaultTPD
			if tpd <= 0 {
				tpd = meta.DefaultTPD
			}

			// Apply limits_override on top of merged defaults
			rpm, rpd, tpm, tpd = ApplyLimitsOverride(rpm, rpd, tpm, tpd, fp.LimitsOverride)

			depID := deploymentID(providerName, keyHash)
			autoDeployments[depID] = DeploymentConfig{
				ID:                    depID,
				Enabled:               true,
				ChannelID:             0, // filled after channel insert/update
				RealModel:             realModel,
				Pool:                  "free",
				QualityTier:           "medium",
				CostTier:              "free",
				SupportsVision:        meta.SupportsVision,
				SupportsStream:        meta.SupportsStream,
				SupportsTools:         meta.SupportsTools,
				SupportsJSON:          meta.SupportsJSON,
				ContextLength:         meta.ContextLength,
				Priority:              10,
				Weight:                100,
				MaxConcurrentRequests: 5,
				QuotaMode:             "free",
				SoftLimitRatio:        0.95,
				HardLimitRatio:        1.0,
				RPMLimit:              rpm,
				RPDLimit:              rpd,
				TPMLimit:              tpm,
				TPDLimit:              tpd,
			}
		}
	}

	// 3. Reconcile channels
	for _, d := range desiredChannels {
		existingCh, found := existingByName[d.name]
		if found {
			// Update if key changed
			if existingCh.Key != d.ch.Key {
				existingCh.Key = d.ch.Key
				existingCh.Models = d.ch.Models
				existingCh.Type = d.ch.Type
				if err := model.DB.Model(existingCh).Updates(map[string]interface{}{
					"key":    existingCh.Key,
					"models": existingCh.Models,
					"type":   existingCh.Type,
				}).Error; err != nil {
					logger.SysError(fmt.Sprintf("[free_pool] failed to update channel %s: %v", d.name, err))
					continue
				}
				_ = existingCh.UpdateAbilities()
				logger.SysWarn(fmt.Sprintf("[free_pool] auto channel %s (id=%d) key updated — config sync overwrote previous key", d.name, existingCh.Id))
			}
			// Ensure enabled
			if existingCh.Status != model.ChannelStatusEnabled {
				model.UpdateChannelStatusById(existingCh.Id, model.ChannelStatusEnabled)
			}
			// Fill ChannelID in deployment
			depID := deploymentID(d.provider, d.keyHash)
			if dep, ok := autoDeployments[depID]; ok {
				dep.ChannelID = existingCh.Id
				autoDeployments[depID] = dep
			}
		} else {
			// Create new channel
			if err := d.ch.Insert(); err != nil {
				logger.SysError(fmt.Sprintf("[free_pool] failed to insert channel %s: %v", d.name, err))
				continue
			}
			// Fill ChannelID in deployment
			depID := deploymentID(d.provider, d.keyHash)
			if dep, ok := autoDeployments[depID]; ok {
				dep.ChannelID = d.ch.Id
				autoDeployments[depID] = dep
			}
		}
	}

	// 4. Disable removed channels
	for _, existingCh := range existing {
		stillNeeded := false
		for _, d := range desiredChannels {
			if d.name == existingCh.Name {
				stillNeeded = true
				break
			}
		}
		if !stillNeeded && existingCh.Status == model.ChannelStatusEnabled {
			model.UpdateChannelStatusById(existingCh.Id, model.ChannelStatusManuallyDisabled)
			logger.SysLog(fmt.Sprintf("[free_pool] disabled removed auto channel %s (id=%d)", existingCh.Name, existingCh.Id))
		}
	}

	// 5. Write auto deployments into cfg.Deployments (merge, don't wipe).
	// Only write deployments whose ID matches IsAutoDeploymentID — user-created
	// deployments with a "free:*" prefix are preserved and never overwritten.
	if cfg.Deployments == nil {
		cfg.Deployments = map[string]DeploymentConfig{}
	}
	for id, dep := range autoDeployments {
		if dep.ChannelID <= 0 {
			logger.SysWarn(fmt.Sprintf("[free_pool] skipping deployment %s with no channel", id))
			continue
		}
		cfg.Deployments[id] = dep
	}

	// 6. Clean up stale auto deployments: remove from cfg.Deployments any auto
	// deployment that no longer has a corresponding enabled channel.
	for id := range cfg.Deployments {
		if !IsAutoDeploymentID(id) {
			continue // skip user-created deployments
		}
		if _, active := autoDeployments[id]; !active {
			// Stale: either the provider was disabled or the key was removed.
			// Remove it from the config so it won't be considered for routing.
			delete(cfg.Deployments, id)
			logger.SysLog(fmt.Sprintf("[free_pool] removed stale auto deployment %s (channel no longer active)", id))
		}
	}

	return nil
}

func ValidateFreeProviderName(name string) error {
	if _, ok := BuiltinFreeProviders[name]; !ok {
		known := make([]string, 0, len(BuiltinFreeProviders))
		for k := range BuiltinFreeProviders {
			known = append(known, k)
		}
		return fmt.Errorf("unknown free provider %q, known: %s", name, strings.Join(known, ", "))
	}
	return nil
}

func init() {
	_ = time.Now
}

// ApplyLimitsOverride applies limits_override fields on top of existing int values.
// Each non-nil pointer in override replaces the corresponding value.
// Zero means unlimited (valid). Negative values should be rejected by ValidateFreeProviderLimits
// before reaching this function.
func ApplyLimitsOverride(rpm, rpd, tpm, tpd int, override *FreeProviderLimits) (int, int, int, int) {
	if override == nil {
		return rpm, rpd, tpm, tpd
	}
	if override.RPMLimit != nil {
		rpm = *override.RPMLimit
	}
	if override.RPDLimit != nil {
		rpd = *override.RPDLimit
	}
	if override.TPMLimit != nil {
		tpm = *override.TPMLimit
	}
	if override.TPDLimit != nil {
		tpd = *override.TPDLimit
	}
	return rpm, rpd, tpm, tpd
}

// ValidateFreeProviderLimits checks that all limits_override values are >= 0.
func ValidateFreeProviderLimits(limits *FreeProviderLimits) error {
	if limits == nil {
		return nil
	}
	if limits.RPMLimit != nil && *limits.RPMLimit < 0 {
		return fmt.Errorf("rpm_limit must be >= 0, got %d", *limits.RPMLimit)
	}
	if limits.RPDLimit != nil && *limits.RPDLimit < 0 {
		return fmt.Errorf("rpd_limit must be >= 0, got %d", *limits.RPDLimit)
	}
	if limits.TPMLimit != nil && *limits.TPMLimit < 0 {
		return fmt.Errorf("tpm_limit must be >= 0, got %d", *limits.TPMLimit)
	}
	if limits.TPDLimit != nil && *limits.TPDLimit < 0 {
		return fmt.Errorf("tpd_limit must be >= 0, got %d", *limits.TPDLimit)
	}
	return nil
}

// StaleCleanupReport describes auto-generated resources that exist but no longer
// have a corresponding entry in the current free_providers config.
type StaleCleanupReport struct {
	StaleChannels    []StaleItem `json:"stale_channels"`
	StaleDeployments []StaleItem `json:"stale_deployments"`
	WillDelete       bool        `json:"will_delete"`
}

// StaleItem represents a single stale auto resource.
type StaleItem struct {
	Name   string `json:"name"`
	ID     int    `json:"id,omitempty"`
	Reason string `json:"reason"`
}

// computeExpectedAutoResources computes the set of expected auto channel names
// and deployment IDs from the current FreeProviders config. Used by both
// DryRunCleanStale and tests to determine which auto resources are still valid.
func computeExpectedAutoResources(cfg *Config) (expectedChannels map[string]bool, expectedDeployments map[string]bool) {
	expectedChannels = make(map[string]bool)
	expectedDeployments = make(map[string]bool)

	for providerName, fp := range cfg.FreeProviders {
		if !fp.Enabled || len(fp.Keys) == 0 {
			continue
		}
		if _, ok := BuiltinFreeProviders[providerName]; !ok {
			continue
		}
		for _, key := range fp.Keys {
			if strings.TrimSpace(key) == "" {
				continue
			}
			keyHash := SafeKeyHash(key)
			expectedChannels[channelName(providerName, keyHash)] = true
			expectedDeployments[deploymentID(providerName, keyHash)] = true
		}
	}
	return expectedChannels, expectedDeployments
}

// DryRunCleanStale returns a report of stale auto resources (channels and
// deployments) that exist in the DB or config but no longer have a matching
// entry in the current free_providers config. Does NOT mutate any state.
// Report is non-nil even when an error is returned.
func DryRunCleanStale() (*StaleCleanupReport, error) {
	cfg := GetConfig()
	if cfg == nil {
		return &StaleCleanupReport{WillDelete: false}, fmt.Errorf("config is nil")
	}

	report := &StaleCleanupReport{WillDelete: false}
	expectedChannels, expectedDeployments := computeExpectedAutoResources(cfg)

	// Scan DB for auto channels that no longer have a matching config entry
	if model.DB == nil {
		return report, fmt.Errorf("database not initialized")
	}

	var dbChannels []*model.Channel
	if err := model.DB.Where("name LIKE ?", autoChannelPrefix+"%").Find(&dbChannels).Error; err != nil {
		return report, fmt.Errorf("failed to query auto channels: %w", err)
	}

	for _, ch := range dbChannels {
		if !expectedChannels[ch.Name] {
			report.StaleChannels = append(report.StaleChannels, StaleItem{
				Name:   ch.Name,
				ID:     ch.Id,
				Reason: "not found in current free_providers config",
			})
		}
	}

	// Scan config deployments for auto deployments that no longer have a matching key
	if cfg.Deployments != nil {
		for id, dep := range cfg.Deployments {
			if !IsAutoDeploymentID(id) {
				continue
			}
			if !expectedDeployments[id] {
				report.StaleDeployments = append(report.StaleDeployments, StaleItem{
					Name:   id,
					ID:     dep.ChannelID,
					Reason: "not found in current free_providers config",
				})
			}
		}
	}

	// Sort for deterministic output
	sort.Slice(report.StaleChannels, func(i, j int) bool {
		return report.StaleChannels[i].Name < report.StaleChannels[j].Name
	})
	sort.Slice(report.StaleDeployments, func(i, j int) bool {
		return report.StaleDeployments[i].Name < report.StaleDeployments[j].Name
	})

	return report, nil
}
